[package]
edition = "2018"
name = "arnau_whirl"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "1"
toml = "0.5.8"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
